#!/usr/bin/env python3

import spacy
from textblob import TextBlob
import random

nlp = spacy.load("en_core_web_sm")
name = None
should_exit = False


# Liste de réponses possibles
responses = {
    "en": {
        "hello": ["Hello, {}!", "Hi there, {}!", "Nice to meet you, {}!"],
        "how are you": ["I'm doing well, thank you.", "Pretty good, thanks for asking.", "Not too bad, how about you?"],
        "goodbye": ["Goodbye, {}!", "See you later, {}!", "Until next time, {}!"],
        "what's your name": ["I'm a chatbot.", "I don't have a name, I'm just a bot.", "You can call me Chatbot!"],
        "tell me a joke": ["Why don't scientists trust atoms? Because they make up everything!", "I told my wife she should embrace her mistakes. She hugged me.", "Why don't skeletons fight each other? They don't have the guts!"],
        "tell me a dad joke": ["I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.", "I don't trust stairs. They're always up to something.", "What do you call someone with no body and no nose? Nobody knows.", "What do you call someone with no body and no nose? Nobody knows."]
    }
}

# Fonction pour répondre à l'utilisateur
def respond(user_input, name):
    # Détecter le nom de l'utilisateur
    doc = nlp(user_input)
    # Détecter la polarité et la subjectivité du texte de l'utilisateur
    blob = TextBlob(user_input)
    polarity = blob.sentiment.polarity
    subjectivity = blob.sentiment.subjectivity
    # Choisir une réponse appropriée en fonction de l'entrée utilisateur
    if "hello" in user_input.lower():
        response = random.choice(responses["en"]["hello"]).format(name)
    elif "how are you" in user_input.lower():
        response = random.choice(responses["en"]["how are you"])
    elif "goodbye" in user_input.lower():
        response = random.choice(responses["en"]["goodbye"]).format(name)
        print("Bot:", response)
        return True  # Set the flag to exit the loop
    elif "what's your name" in user_input.lower():
        response = random.choice(responses["en"]["what's your name"])
    elif "tell me a joke" in user_input.lower():
        response = random.choice(responses["en"]["tell me a joke"])
    elif "tell me a dad joke" in user_input.lower():
        response = random.choice(responses["en"]["tell me a dad joke"])
    #############
    #À completer#
    #############
    print("Bot:", response)
    return False  # Continue the loop

# Boucle principale pour le chatbot
while True:
    if (name == None):
        print("Bot: Hello, what's your name ?")
        name = input("You: ")
        print("Bot: Nice to meet you", name)
    else:
        user_input = input("You: ")
        bot_response = respond(user_input, name)
        print("Bot:", bot_response)
